#---------------------------------------------------------------
#                        Informação
#---------------------------------------------------------------
# autor: Leonardo Viana Pereira
# email: leonardo.viana@armateus.com.br
# empresa: Ithappens
# version: 0.1.0
# Descrição: Ambiente com o zabbix, postgresql e grafana
#---------------------------------------------------------------
#   CONTAINERS
#---------------------------------------------------------------
# - ZABBIX SERVER
# - POSTGRESQL
# - GRAFANA
# - ZABBIX AGENT
# - ZABBIX WEB
#---------------------------------------------------------------
#   REDES:
#---------------------------------------------------------------
# - frontend
# - middle
# - backend
#---------------------------------------------------------------

  version: '3.5'
  services:

#---------------------------------------------------------------
#  Zabbix-Server 
#---------------------------------------------------------------
    server:
      image: zabbix/zabbix-server-pgsql
      container_name: zabbix-server
      restart: always
      user: root
      depends_on:
        - pgsql
      environment:
        TZ: America/Fortaleza
        DB_SERVER_HOST: "pgsql"
        POSTGRES_DB: "zabbix"
        POSTGRES_USER: "zabbix"
        POSTGRES_PASSWORD: "zabbix.123"
        ZBX_DEBUGLEVEL: 2
      ports:
        - "10051:10051"
      volumes:
        - ./usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      links:
        - pgsql:zabbix-pgsql
      networks:
        - middle
        - backend
      

#---------------------------------------------------------------
#  Zabbix-Agent
#---------------------------------------------------------------

    agent:
      image: zabbix/zabbix-agent:latest
      container_name: zabbix-agent
      restart: always
      privileged: true
      depends_on:
        - server
      links:
        - server:zabbix-server
      environment:
        ZBX_HOSTNAME: "server"
        ZBX_SERVER_HOST: "server"
      networks:
        - middle
      

#---------------------------------------------------------------
#  Zabbix-Web : Inteface web do Zabbix
#---------------------------------------------------------------

    web:
      image: zabbix/zabbix-web-nginx-pgsql
      container_name: zabbix-web
      restart: always
      depends_on:
        - pgsql
        - server
      environment:
        PHP_TZ: America/Fortaleza
        DB_SERVER_HOST: "pgsql"
        ZBX_SERVER_HOST: "server"
        POSTGRES_DB: "zabbix"
        POSTGRES_USER: "zabbix"
        POSTGRES_PASSWORD: "zabbix.123"
      links:
        - pgsql:zabbix-pgsql
        - server:zabbix-server
      ports:
        - "81:80"
        - "443:8443"
      networks:
        - frontend
        - backend
        - middle
      

#---------------------------------------------------------------
#  Banco de dados : PostgreSQL
#---------------------------------------------------------------

    pgsql:
      image: postgres:latest
      container_name: zabbix-pgsql
      restart: always
      environment:
        TZ: America/Fortaleza
        POSTGRES_DB: "zabbix"
        POSTGRES_USER: "zabbix"
        POSTGRES_PASSWORD: "zabbix.123"
      networks:
        - backend
      volumes:
        - ./pgsql:/var/lib/postgresql/data
            

#---------------------------------------------------------------
#  Grafana 
#---------------------------------------------------------------

    grafana:
      image: grafana/grafana
      container_name: grafana
      restart: always
      user: root
      depends_on:
        - pgsql
        - server
      environment:
        TZ: America/Fortaleza
        GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app
      ports:
        - 3000:3000
      links:
        - pgsql:zabbix-pgsql
        - server:zabbix-server
      networks:
        - frontend
      volumes:
        - ./grafana:/var/lib/grafana
      
#---------------------------------------------------------------
# NETWORKS
#---------------------------------------------------------------
  networks: 
    frontend: 
    middle: 
    backend:
